from __future__ import annotations

import re


_ALIASES: dict[str, str] = {
    "sle": "systemic lupus erythematosus",
    "systemic lupus erythematosus": "systemic lupus erythematosus",
    "nxg": "necrobiotic xanthogranuloma",
    "necrobiotic xanthogranuloma": "necrobiotic xanthogranuloma",
    "extra nodal rdd": "rosai dorfman destombes disease",
    "extranodal rdd": "rosai dorfman destombes disease",
    "rdd": "rosai dorfman destombes disease",
    "rosai dorfman destombes disease": "rosai dorfman destombes disease",
    "e granulosus": "echinococcosis",
    "echinococ": "echinococcosis",
    "echinococcal infection": "echinococcosis",
    "hydatid disease": "echinococcosis",
    "hydatid cyst": "echinococcosis",
    "echinococcus granulosus": "echinococcosis",
    "echinococcosis": "echinococcosis",
    "ivc aneurysm": "inferior vena cava aneurysm",
    "inferior vena cava aneurysm": "inferior vena cava aneurysm",
    "inferior vena cava aneurysm with renal vein thrombosis": "inferior vena cava aneurysm",
    "tumor induced osteomalacia": "tumor induced osteomalacia",
    "tumor-induced osteomalacia": "tumor induced osteomalacia",
    "tumour induced osteomalacia": "tumor induced osteomalacia",
    "tumour-induced osteomalacia": "tumor induced osteomalacia",
    "invasive ductal carcinoma": "breast cancer",
    "breast carcinoma": "breast cancer",
    "breast cancer": "breast cancer",
    "bilateral poland syndrome": "poland syndrome",
    "poland syndrome": "poland syndrome",
    "cah": "congenital adrenal hyperplasia",
    "congenital adrenal hyperplasia": "congenital adrenal hyperplasia",
    "salt wasting form": "congenital adrenal hyperplasia",
    "salt wasting congenital adrenal hyperplasia": "congenital adrenal hyperplasia",
    "pmts": "tumor induced osteomalacia",
    "pmt": "tumor induced osteomalacia",
    "phosphaturic mesenchymal tumor": "tumor induced osteomalacia",
    "n stemi": "acute non st elevation myocardial infarction",
    "nstemi": "acute non st elevation myocardial infarction",
    "non stemi": "acute non st elevation myocardial infarction",
    "acute non stemi": "acute non st elevation myocardial infarction",
    "acute non-stemi": "acute non st elevation myocardial infarction",
    "acute non st segment elevation myocardial infarction": "acute non st elevation myocardial infarction",
    "acute non st-segment elevation myocardial infarction": "acute non st elevation myocardial infarction",
    "non st-segment elevation myocardial infarction": "acute non st elevation myocardial infarction",
    "non st elevation myocardial infarction": "acute non st elevation myocardial infarction",
    "non st segment elevation myocardial infarction": "acute non st elevation myocardial infarction",
    "acute non st elevation myocardial infarction": "acute non st elevation myocardial infarction",
    "stemi": "acute st elevation myocardial infarction",
    "acute st elevation myocardial infarction": "acute st elevation myocardial infarction",
    "bac": "bronchioloalveolar carcinoma",
    "non mucinous bac": "bronchioloalveolar carcinoma",
    "bronchioloalveolar carcinoma": "bronchioloalveolar carcinoma",
    "bronchioalveolar carcinoma": "bronchioloalveolar carcinoma",
    "egfr exon 19": "egfr mutated lung adenocarcinoma",
    "egfr exon 19 deletion": "egfr mutated lung adenocarcinoma",
    "egfr mutated lung adenocarcinoma": "egfr mutated lung adenocarcinoma",
    "lung adenocarcinoma": "lung adenocarcinoma",
    "pdac": "pancreatic ductal adenocarcinoma",
    "pancreatic ductal adenocarcinoma": "pancreatic ductal adenocarcinoma",
    "borderline resectable pdac": "pancreatic ductal adenocarcinoma",
    "gist": "gastrointestinal stromal tumor",
    "gist histology": "gastrointestinal stromal tumor",
    "gastrointestinal stromal tumor": "gastrointestinal stromal tumor",
    "dmmr": "mismatch repair deficiency",
    "mismatch repair deficiency": "mismatch repair deficiency",
    "covid 19": "covid 19",
    "covid-19": "covid 19",
    "papillary thyroid cancer": "papillary thyroid cancer",
    "papillary thyroid carcinoma": "papillary thyroid cancer",
    "papillary carcinoma thyroid": "papillary thyroid cancer",
    "papillary carcinoma thyroid left lobe": "papillary thyroid cancer",
    "papillary carcinoma thyroid right lobe": "papillary thyroid cancer",
    "papillary carcinoma thyroid isthmus": "papillary thyroid cancer",
    "brain metastases": "brain metastasis",
    "brain metastasis": "brain metastasis",
    "peritoneal carcinomatosis": "peritoneal carcinomatosis",
    "severe aortic stenosis": "aortic stenosis",
    "aortic stenosis": "aortic stenosis",
    "uterine leiomyoma": "leiomyoma",
    "leiomyoma": "leiomyoma",
    "fibroid": "leiomyoma",
    "brain metastases": "brain metastasis",
    "brain mets": "brain metastasis",
    "metastatic brain lesion": "brain metastasis",
    "metastatic brain lesions": "brain metastasis",
    "hiv": "hiv infection",
    "hiv infection": "hiv infection",
    "immune reconstitution inflammatory syndrome": "iris",
    "iris": "iris",
    "coccidioidal meningitis": "coccidioidal meningitis",
    "coccidioidomycosis meningitis": "coccidioidal meningitis",
    "recurrent contralateral pneumothorax": "recurrent contralateral pneumothorax",
    "contralateral pneumothorax": "recurrent contralateral pneumothorax",
    "recurrent pneumothorax": "recurrent contralateral pneumothorax",
    "azygos lobe": "azygos lobe",
    "azygos vein anomaly": "azygos lobe",
    "canine parvovirus": "parvoviral enteritis",
    "canine parvoviral enteritis": "parvoviral enteritis",
    "parvoviral enteritis": "parvoviral enteritis",
    "feline infectious peritonitis": "feline infectious peritonitis",
    "fip": "feline infectious peritonitis",
    "equine colic": "equine colic",
    "bovine respiratory disease": "bovine respiratory disease",
    "mastitis": "mastitis",
    "canine distemper": "canine distemper",
    "sdl tga": "sdl tga",
    "d tga": "transposition of the great arteries",
    "tga": "transposition of the great arteries",
    "transposition of the great arteries": "transposition of the great arteries",
    "ventricular septal defect": "ventricular septal defect",
    "vsd": "ventricular septal defect",
    "atrial septal defect": "atrial septal defect",
    "asd": "atrial septal defect",
    "congenital heart defect": "congenital heart defect",
    "chd": "congenital heart defect",
    "single ventricle physiology": "single ventricle physiology",
    "single-ventricle physiology": "single ventricle physiology",
    "unbalanced atrioventricular canal": "unbalanced atrioventricular canal",
    "pulmonary stenosis": "pulmonary stenosis",
    "severe pulmonary stenosis": "pulmonary stenosis",
    "situs ambiguous": "situs ambiguous",
    "abdominal situs ambiguous": "situs ambiguous",
    "adrenocortical insufficiency": "adrenocortical insufficiency",
    "adrenal insufficiency": "adrenocortical insufficiency",
    "hypopituitarism": "hypopituitarism",
    "pancytopenia": "pancytopenia",
    "hypothyroidism": "hypothyroidism",
    "disseminated tuberculosis": "disseminated tuberculosis",
    "tb": "tuberculosis",
    "tuberculosis": "tuberculosis",
    "diabetes mellitus": "diabetes mellitus",
    "type 2 diabetes mellitus": "type 2 diabetes mellitus",
    "diabetic ketoacidosis": "diabetic ketoacidosis",
    "diabetic foot ulcer": "diabetes mellitus",
    "osteomyelitis": "osteomyelitis",
    "cellulitis": "cellulitis",
    "neuropathy": "neuropathy",
    "granuloma annulare": "granuloma annulare",
    "common bile duct perforation": "common bile duct perforation",
    "biliary peritonitis": "biliary peritonitis",
    "ulcerous acalculous cholecystitis": "ulcerous acalculous cholecystitis",
    "rhino sinusitis": "rhino sinusitis",
    "chronic sinusitis": "chronic sinusitis",
    "hidrotic ectodermal dysplasia": "hidrotic ectodermal dysplasia",
    "hypohidrotic ectodermal dysplasia": "hed",
    "hed": "hed",
    "nail dysplasia": "nail dysplasia",
    "hair dysplasia": "hair dysplasia",
    "hyperkeratosis": "hyperkeratosis",
    "arteriocolonic fistula": "arteriocolonic fistula",
    "inferior mesenteric artery aneurysm": "inferior mesenteric artery aneurysm",
    "ischemic colitis": "ischemic colitis",
    "sigmoid colon inflammation": "sigmoid colon inflammation",
    "pulmonary thromboembolism": "pulmonary thromboembolism",
    "tuberculous pleurisy": "tuberculous pleurisy",
    "primary malignant melanoma of the esophagus": "esophageal melanoma",
    "esophageal melanoma": "esophageal melanoma",
    "malignant melanoma of esophagus": "esophageal melanoma",
    "pmme": "esophageal melanoma",
    "ecd": "erdheim chester disease",
    "erdheim chester disease": "erdheim chester disease",
    "erdheim-chester disease": "erdheim chester disease",
    "pericardial effusion": "pericardial effusion",
    "retroperitoneal fibrosis": "retroperitoneal fibrosis",
    "hydronephrosis": "hydronephrosis",
    "gi melanoma": "gastrointestinal melanoma",
    "gastrointestinal melanoma": "gastrointestinal melanoma",
    "malignant melanoma of the small bowel": "gastrointestinal melanoma",
    "small bowel melanoma": "gastrointestinal melanoma",
    "iron deficiency anemia": "iron deficiency anemia",
    "pnen": "pancreatic neuroendocrine neoplasm",
    "pancreatic neuroendocrine neoplasm": "pancreatic neuroendocrine neoplasm",
    "pvtt": "portal vein tumor thrombosis",
    "portal vein tumor thrombosis": "portal vein tumor thrombosis",
    "portal vein invasion": "portal vein tumor thrombosis",
    "gastric varices": "gastric varices",
    "splenoportomesenteric hypertension": "splenoportomesenteric hypertension",
    "pancreatitis": "pancreatitis",
    "pancoast tumor": "pancoast tumor",
    "pancoast syndrome": "pancoast syndrome",
    "egpa": "eosinophilic granulomatosis with polyangiitis",
    "eosinophilic granulomatosis with polyangiitis": "eosinophilic granulomatosis with polyangiitis",
    "eosinophilic gastroenteritis": "eosinophilic gastroenteritis",
    "atrioventricular block": "atrioventricular block",
    "cardiac arrest": "cardiac arrest",
    "allergic asthma": "allergic asthma",
    "asthma": "asthma",
    "osteoarthritis": "osteoarthritis",
    "septic arthritis": "septic arthritis",
    "mycobacterium persicum infection": "mycobacterium persicum infection",
    "congenital hip defects": "congenital hip defect",
    "congenital hip defect": "congenital hip defect",
    "avm": "arteriovenous malformation",
    "arteriovenous malformation": "arteriovenous malformation",
    "ich": "intracerebral hemorrhage",
    "intracerebral hemorrhage": "intracerebral hemorrhage",
    "epilepsy": "epilepsy",
    "copd": "chronic obstructive pulmonary disease",
    "chronic obstructive pulmonary disease": "chronic obstructive pulmonary disease",
    "hfr ef": "heart failure with reduced ejection fraction",
    "hfref": "heart failure with reduced ejection fraction",
    "heart failure with reduced ejection fraction": "heart failure with reduced ejection fraction",
    "mca ischemic stroke": "middle cerebral artery ischemic stroke",
    "middle cerebral artery ischemic stroke": "middle cerebral artery ischemic stroke",
    "ischemic stroke": "ischemic stroke",
    "gallstone ileus": "gallstone ileus",
    "cholelithiasis": "cholelithiasis",
    "cholecystocolonic fistula": "cholecystocolonic fistula",
    "systemic lupus erythematosus": "systemic lupus erythematosus",
    "antiphospholipid syndrome": "antiphospholipid syndrome",
    "raynaud s phenomenon": "raynaud phenomenon",
    "raynaud phenomenon": "raynaud phenomenon",
    "microvascular angina": "microvascular angina",
    "umbilical hernia": "umbilical hernia",
    "tracer site hernia": "tracer site hernia",
    "small bowel herniation": "small bowel herniation",
    "ileus": "ileus",
    "synovial sarcoma": "synovial sarcoma",
    "monophasic synovial sarcoma": "synovial sarcoma",
    "ss monophasic": "synovial sarcoma",
    "pulmonary metastasis": "pulmonary metastasis",
    "pathological fracture": "pathological fracture",
    "anemia": "anemia",
    "constrictive pericarditis": "constrictive pericarditis",
    "pericardial mesothelioma": "pericardial mesothelioma",
    "tuberculous pericarditis": "tuberculous pericarditis",
    "renal cell carcinoma": "renal cell carcinoma",
    "cystic kidney cancer": "renal cell carcinoma",
    "papillary renal cell carcinoma": "renal cell carcinoma",
    "papillary renal cell carcinoma type 2": "renal cell carcinoma",
    "invasive ductal carcinoma of the breast": "breast cancer",
    "endometrial cancer regimen": "endometrial cancer",
    "endometrial cancer": "endometrial cancer",
    "primary lung signet ring cell carcinoma": "primary lung signet ring cell carcinoma",
    "metastatic primary lung srcc": "primary lung signet ring cell carcinoma",
    "srcc": "primary lung signet ring cell carcinoma",
    "end stage chronic kidney disease": "end stage chronic kidney disease",
    "iga nephropathy": "iga nephropathy",
    "atrial fibrillation": "atrial fibrillation",
    "arterial hypertension": "arterial hypertension",
    "aortic aneurysm": "aortic aneurysm",
    "ascending aortic aneurysm": "aortic aneurysm",
    "aortic valve insufficiency": "aortic valve insufficiency",
    "wiskott aldrich syndrome": "wiskott aldrich syndrome",
    "eczema": "eczema",
    "vesicovaginal fistula": "vesicovaginal fistula",
    "ureterovaginal fistula": "ureterovaginal fistula",
    "serous cystadenoma": "serous cystadenoma",
    "coronary artery anomaly": "coronary artery anomaly",
    "coronary artery anomalies": "coronary artery anomaly",
    "posterior right diagonal artery variant": "posterior right diagonal artery variant",
    "kidney calculi": "kidney calculi",
    "renal calculi": "kidney calculi",
    "retrocaval ureter": "retrocaval ureter",
    "ureteropelvic junction obstruction": "ureteropelvic junction obstruction",
    "k wire migration": "k wire migration",
    "k-wire migration": "k wire migration",
    "kirschner wire migration": "k wire migration",
    "urinary bladder injury": "urinary bladder injury",
    "bladder injury": "urinary bladder injury",
    "venous malformations": "venous malformation",
    "venous malformation": "venous malformation",
    "hypophosphatemic osteomalacia": "hypophosphatemic osteomalacia",
    "osteomalacia": "osteomalacia",
    "hypogonadotropic hypogonadism": "hypogonadotropic hypogonadism",
    "oligozoospermia": "oligozoospermia",
    "severe oligozoospermia": "oligozoospermia",
    "obesity": "obesity",
    "thrombotic microangiopathy": "thrombotic microangiopathy",
    "hemolytic anemia": "hemolytic anemia",
    "uterine inversion": "uterine inversion",
    "metrorrhagia": "metrorrhagia",
    "colon metastasis": "colon metastasis",
    "colon metastasis of breast cancer": "colon metastasis",
    "cerebrovascular accident": "cerebrovascular accident",
    "lynch syndrome": "lynch syndrome",
    "polio": "poliomyelitis",
    "poliomyelitis": "poliomyelitis",
    "gists": "gastrointestinal stromal tumor",
    "sdha deficient gist": "gastrointestinal stromal tumor",
    "sdha-deficient gist": "gastrointestinal stromal tumor",
    "recurrent sdha deficient gists": "gastrointestinal stromal tumor",
    "good s syndrome": "good syndrome",
    "goods syndrome": "good syndrome",
    "good syndrome": "good syndrome",
    "thymoma": "thymoma",
    "hypogammaglobulinemia": "hypogammaglobulinemia",
    "hgg": "hypogammaglobulinemia",
    "oral lichen planus": "oral lichen planus",
    "patent foramen ovale": "patent foramen ovale",
    "pfo": "patent foramen ovale",
    "pulmonary emboli": "pulmonary embolism",
    "pulmonary embolism": "pulmonary embolism",
    "cryptogenic stroke": "cryptogenic stroke",
    "watershed stroke": "cryptogenic stroke",
    "thrombophilia": "thrombophilia",
    "factor ii gene mutation": "factor ii gene mutation",
    "prothrombin gene mutation": "prothrombin gene mutation",
    "pai 1 4g 5g gene polymorphism": "pai 1 4g 5g gene polymorphism",
    "intracerebral hemorrhage": "intracerebral hemorrhage",
    "ich": "intracerebral hemorrhage",
    "primary lung signet ring cell carcinoma": "primary lung signet ring cell carcinoma",
    "iga nephropathy": "iga nephropathy",
    "atrial fibrillation": "atrial fibrillation",
    "mitral stenosis": "mitral stenosis",
    "mitral regurgitation": "mitral regurgitation",
    "aortic regurgitation": "aortic regurgitation",
    "ventricular tachycardia": "ventricular tachycardia",
    "supraventricular tachycardia": "supraventricular tachycardia",
    "partial anomalous pulmonary venous connection": "partial anomalous pulmonary venous connection",
    "papvc": "partial anomalous pulmonary venous connection",
    "regressed left ventricle": "regressed left ventricle",
    "intestinal malrotation": "intestinal malrotation",
    "duodenal web": "duodenal web",
    "lupus nephritis": "lupus nephritis",
    "dysphagia": "dysphagia",
    "hoarseness of voice": "hoarseness of voice",
    "hematochezia": "hematochezia",
    "sigmoid colon inflammation": "sigmoid colon inflammation",
    "epidermoid cyst": "epidermoid cyst",
    "epidermal cyst": "epidermoid cyst",
    "mediastinal abscess": "mediastinal abscess",
    "pyopericardium": "pyopericardium",
    "non small cell lung cancer": "non small cell lung cancer",
    "nsclc": "non small cell lung cancer",
    "phimosis": "phimosis",
    "splenic hemangioma": "splenic hemangioma",
    "hypersplenism": "hypersplenism",
    "multiple myeloma": "multiple myeloma",
    "chronic liver disease": "chronic liver disease",
    "displacement of maxillary third molar into the infratemporal fossa": "displacement of maxillary third molar into the infratemporal fossa",
    "impacted tooth in infratemporal fossa": "displacement of maxillary third molar into the infratemporal fossa",
    "tooth into ipsilateral infratemporal fossa": "displacement of maxillary third molar into the infratemporal fossa",
    "hematoma or hemangioma": "hematoma or hemangioma",
    "hematoma": "hematoma or hemangioma",
    "seborrheic keratosis": "seborrheic keratosis",
    "metastatic colorectal cancer": "metastatic colorectal cancer",
    "liver metastasis of intestinal type adenocarcinoma": "metastatic colorectal cancer",
    "hodgkin lymphoma": "hodgkin lymphoma",
    "classical hodgkin lymphoma of mixed cellularity": "classical hodgkin lymphoma of mixed cellularity",
    "tm": "transverse myelitis",
    "tm with hz": "transverse myelitis",
    "transverse myelitis": "transverse myelitis",
    "herpes zoster": "herpes zoster",
    "hz": "herpes zoster",
    "mixed neuroendocrine non neuroendocrine tumor of the gallbladder": "gallbladder cancer",
    "minen of the gallbladder": "gallbladder cancer",
    "gb minen": "gallbladder cancer",
    "gb cancer": "gallbladder cancer",
    "gallbladder cancer": "gallbladder cancer",
    "gb cancer": "gallbladder cancer",
    "gallbladder adenocarcinoma": "gallbladder adenocarcinoma",
    "large cell neuroendocrine carcinoma": "large cell neuroendocrine carcinoma",
    "lcnec": "large cell neuroendocrine carcinoma",
    "neuroendocrine tumor": "neuroendocrine tumor",
    "s brasiliensis": "sporotrichosis",
    "sporothrix brasiliensis": "sporotrichosis",
    "sporotrichosis": "sporotrichosis",
    "feline sporotrichosis": "feline sporotrichosis",
    "sdha deficient gastrointestinal stromal tumor": "gastrointestinal stromal tumor",
    "spindle cell sclerosing rhabdomyosarcoma": "spindle cell sclerosing rhabdomyosarcoma",
    "rhabdomyosarcoma high grade spindle cell sclerosing type": "spindle cell sclerosing rhabdomyosarcoma",
    "crush injury of the left lower extremity": "crush injury of the left lower extremity",
    "invasive mucinous adenocarcinoma": "invasive mucinous adenocarcinoma",
    "cerebral mucormycosis": "cerebral mucormycosis",
    "mucormycosis": "cerebral mucormycosis",
    "malrotation": "intestinal malrotation",
    "migraine": "migraine",
    "migraines": "migraine",
    "allergic rhinitis": "allergic rhinitis",
    "uterine fibroids": "uterine fibroids",
    "uterine fibroid": "uterine fibroids",
    "tooth displacement into infratemporal fossa": "displacement of maxillary third molar into the infratemporal fossa",
    "cystic lymphangioma": "cardiac lymphangioma",
    "cardiac lymphangioma": "cardiac lymphangioma",
    "oropharyngeal and neck masses causing airway compromise": "dyspnea associated",
    "oropharyngeal and neck masses": "dyspnea associated",
    "dyspnea associated": "dyspnea associated",
    "dyspnea": "dyspnea",
    "oropharyngeal and neck masses": "oropharyngeal and neck masses",
    "difficult airway": "difficult airway",
    "pulmonary arrest": "pulmonary arrest",
    "brain injury": "brain injury",
    "hepatitis b": "hepatitis b",
    "persistent dry cough": "persistent dry cough",
    "neuropathic ulcer": "neuropathy",
    "neuropathy": "neuropathy",
    "cellulitis": "cellulitis",
    "monoclonal gammopathy": "monoclonal gammopathy",
    "polyneuropathy": "polyneuropathy",
    "intracerebral hemorrhage ich": "intracerebral hemorrhage",
    "hemorrhage ich": "intracerebral hemorrhage",
    "rheumatic heart disease": "rheumatic heart disease",
    "mitral regurgitation": "mitral regurgitation",
    "aortic regurgitation": "aortic regurgitation",
    "ventricular tachycardia": "ventricular tachycardia",
    "supraventricular tachycardia": "supraventricular tachycardia",
}


def normalize_text_for_terms(text: str) -> str:
    text = str(text).lower().replace("-", " ")
    text = re.sub(r"[^a-z0-9]+", " ", text)
    return re.sub(r"\s+", " ", text).strip()


def canonicalize_diagnosis(text: str, *, enabled: bool = True) -> str:
    if not enabled:
        return str(text)
    raw = str(text)
    low = normalize_text_for_terms(raw)
    if not low:
        return raw
    if re.search(r"\bbac\b", low) or "bronchioloalveolar carcinoma" in low or "bronchioalveolar carcinoma" in low:
        return "bronchioloalveolar carcinoma"
    for alias, canonical in sorted(_ALIASES.items(), key=lambda item: len(item[0]), reverse=True):
        alias_norm = normalize_text_for_terms(alias)
        if low == alias_norm or re.search(rf"\b{re.escape(alias_norm)}\b", low):
            return canonical
    return raw


def canonicalize_diagnoses(items: list[str], *, enabled: bool = True) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for item in items:
        canonical = canonicalize_diagnosis(item, enabled=enabled).strip()
        key = normalize_text_for_terms(canonical)
        if canonical and key not in seen:
            out.append(canonical)
            seen.add(key)
    return out
